name: checking commit message
on:
  push

jobs:
  checkking:
    runs-on: self-hosted
    steps:
      - name: fetch data
        run: |
         curl --request GET 'https://api.github.com/repos/yash95751/teset/commits/${{github.ref}}' \
          --header 'Accept: application/vnd.github+json' \
          --header 'Authorization: Bearer ${{secrets.YASHTOKEN}}' \
          --header 'Cookie: _octo=GH1.1.856630408.1662440634; logged_in=no' -o data.json
      
      - name: Extract sha
        uses: sergeysova/jq-action@v2
        id: sha
        with:
          cmd: 'jq .sha package.json -r'
      
      - name: Show my version
        run: 'echo "sha ${{ steps.sha.outputs.value }}"'

  
