name: 'Commit Message Check'
on:
  push:
jobs:
  check-commit-message:
    name: Check Commit Message
    runs-on: self-hosted
    steps:
      - name: Check Commit Type
        uses: gsactions/commit-message-checker@v1
        with:
          pattern: '^(((LTKP|LSP|TKP)\-\d{2,4}($|\s|\n))|(Merge branch)|(\d+\.\d+\.\d+)'
          flags: 'gm'
          error: 'Your first line has to contain a commit type like "[JIRA-NUMBER]".'
