name: 'Commit Messages Check'
on:
  push:
#   pull_request:
#     types:
#       - opened
#       - edited
#       - reopened
#       - synchronize
jobs:
  check-commit-message:
    name: Check Commit Message
    runs-on: self-hosted
    steps:
      - name: Check Commit Type
        uses: gsactions/commit-message-checker@v1
        with:
          pattern: '[JIRA\-[0-9]+\]|Merge|merge'
          flags: 'gm'
          error: 'Your first line has to contain  commit messafe type like "[JIRA-NUMBER]".'
