name: 'Commit Message Check'
on:
  push:
    branches:
      - main
      - 'releases/*'
      - newbranch
      - new

jobs:
  check-commit-message:
    name: Check Commit Message
    runs-on: self-hosted
    steps:
      - name: Check Commit Type
        uses: gsactions/commit-message-checker@v1
        with:
          pattern: '\[[^]]+\] .+$'
          flags: 'gm'
          error: 'Your first line has to contain a commit type like "[JIRA-NUMBER]".'
